version: '3.1'
services:
  threatbook-ip-web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: BUILDER
    entrypoint: /bin/sh -c '/app/server'
    ports:
      - "8080:8080"
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./config/config.toml:/app/config/config.toml
