// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/hackerchai/threatbook-ip-web/internal/app/handler"
	"github.com/hackerchai/threatbook-ip-web/internal/app/repository"
	"github.com/hackerchai/threatbook-ip-web/internal/app/service"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeEvent() *Injector {
	app := New()
	client := InitDatabase()
	threatRepo := repository.ThreatRepo{
		DB: client,
	}
	threatSrv := &service.ThreatSrv{
		ThreatRepo: threatRepo,
	}
	threatAPI := &handler.ThreatAPI{
		ThreatSrv: threatSrv,
	}
	handlerHandler := &handler.Handler{
		ThreatAPI: threatAPI,
	}
	injector := &Injector{
		Engine:  app,
		Handler: handlerHandler,
	}
	return injector
}
