[common]
host = "0.0.0.0"
port = 8080
deploy_mode = "development"
swagger = "disable"

[dev_database]
database = "dev"
host = "127.0.0.1"
password = "123456"
port = 5432
username = "root"
ssl_mode = "disable"

[prod_database]
database = "prod"
host = "127.0.0.1"
password = "123456"
port = 5432
username = "root"
ssl_mode = "disable"

[log]
type = "console"
local_time = true
compress = true
max_age = 30
max_size = 100
filename = "log/app.log"
max_backups = 10
level = "info"