// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ThreatColumns holds the columns for the "threat" table.
	ThreatColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ip", Type: field.TypeString, Unique: true},
		{Name: "threat_id_info", Type: field.TypeString},
		{Name: "domain_count", Type: field.TypeInt},
		{Name: "tag_count", Type: field.TypeInt},
		{Name: "itel_count", Type: field.TypeInt},
		{Name: "judge", Type: field.TypeInt},
		{Name: "poc", Type: field.TypeBool},
		{Name: "source", Type: field.TypeInt},
		{Name: "ctime", Type: field.TypeInt64},
	}
	// ThreatTable holds the schema information for the "threat" table.
	ThreatTable = &schema.Table{
		Name:       "threat",
		Columns:    ThreatColumns,
		PrimaryKey: []*schema.Column{ThreatColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ThreatTable,
	}
)

func init() {
	ThreatTable.Annotation = &entsql.Annotation{
		Table: "threat",
	}
}
