// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/hackerchai/threatbook-ip-web/ent/migrate"

	"github.com/hackerchai/threatbook-ip-web/ent/threat"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Threat is the client for interacting with the Threat builders.
	Threat *ThreatClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Threat = NewThreatClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Threat: NewThreatClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Threat: NewThreatClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Threat.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Threat.Use(hooks...)
}

// ThreatClient is a client for the Threat schema.
type ThreatClient struct {
	config
}

// NewThreatClient returns a client for the Threat from the given config.
func NewThreatClient(c config) *ThreatClient {
	return &ThreatClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `threat.Hooks(f(g(h())))`.
func (c *ThreatClient) Use(hooks ...Hook) {
	c.hooks.Threat = append(c.hooks.Threat, hooks...)
}

// Create returns a builder for creating a Threat entity.
func (c *ThreatClient) Create() *ThreatCreate {
	mutation := newThreatMutation(c.config, OpCreate)
	return &ThreatCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Threat entities.
func (c *ThreatClient) CreateBulk(builders ...*ThreatCreate) *ThreatCreateBulk {
	return &ThreatCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Threat.
func (c *ThreatClient) Update() *ThreatUpdate {
	mutation := newThreatMutation(c.config, OpUpdate)
	return &ThreatUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ThreatClient) UpdateOne(t *Threat) *ThreatUpdateOne {
	mutation := newThreatMutation(c.config, OpUpdateOne, withThreat(t))
	return &ThreatUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ThreatClient) UpdateOneID(id int) *ThreatUpdateOne {
	mutation := newThreatMutation(c.config, OpUpdateOne, withThreatID(id))
	return &ThreatUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Threat.
func (c *ThreatClient) Delete() *ThreatDelete {
	mutation := newThreatMutation(c.config, OpDelete)
	return &ThreatDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ThreatClient) DeleteOne(t *Threat) *ThreatDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *ThreatClient) DeleteOneID(id int) *ThreatDeleteOne {
	builder := c.Delete().Where(threat.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ThreatDeleteOne{builder}
}

// Query returns a query builder for Threat.
func (c *ThreatClient) Query() *ThreatQuery {
	return &ThreatQuery{
		config: c.config,
	}
}

// Get returns a Threat entity by its id.
func (c *ThreatClient) Get(ctx context.Context, id int) (*Threat, error) {
	return c.Query().Where(threat.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ThreatClient) GetX(ctx context.Context, id int) *Threat {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ThreatClient) Hooks() []Hook {
	return c.hooks.Threat
}
