// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hackerchai/threatbook-ip-web/ent/threat"
)

// ThreatCreate is the builder for creating a Threat entity.
type ThreatCreate struct {
	config
	mutation *ThreatMutation
	hooks    []Hook
}

// SetIP sets the "ip" field.
func (tc *ThreatCreate) SetIP(s string) *ThreatCreate {
	tc.mutation.SetIP(s)
	return tc
}

// SetThreatIDInfo sets the "threat_id_info" field.
func (tc *ThreatCreate) SetThreatIDInfo(s string) *ThreatCreate {
	tc.mutation.SetThreatIDInfo(s)
	return tc
}

// SetDomainCount sets the "domain_count" field.
func (tc *ThreatCreate) SetDomainCount(i int) *ThreatCreate {
	tc.mutation.SetDomainCount(i)
	return tc
}

// SetTagCount sets the "tag_count" field.
func (tc *ThreatCreate) SetTagCount(i int) *ThreatCreate {
	tc.mutation.SetTagCount(i)
	return tc
}

// SetItelCount sets the "itel_count" field.
func (tc *ThreatCreate) SetItelCount(i int) *ThreatCreate {
	tc.mutation.SetItelCount(i)
	return tc
}

// SetJudge sets the "judge" field.
func (tc *ThreatCreate) SetJudge(i int) *ThreatCreate {
	tc.mutation.SetJudge(i)
	return tc
}

// SetPoc sets the "poc" field.
func (tc *ThreatCreate) SetPoc(b bool) *ThreatCreate {
	tc.mutation.SetPoc(b)
	return tc
}

// SetSource sets the "source" field.
func (tc *ThreatCreate) SetSource(i int) *ThreatCreate {
	tc.mutation.SetSource(i)
	return tc
}

// SetCtime sets the "ctime" field.
func (tc *ThreatCreate) SetCtime(i int64) *ThreatCreate {
	tc.mutation.SetCtime(i)
	return tc
}

// SetID sets the "id" field.
func (tc *ThreatCreate) SetID(i int) *ThreatCreate {
	tc.mutation.SetID(i)
	return tc
}

// Mutation returns the ThreatMutation object of the builder.
func (tc *ThreatCreate) Mutation() *ThreatMutation {
	return tc.mutation
}

// Save creates the Threat in the database.
func (tc *ThreatCreate) Save(ctx context.Context) (*Threat, error) {
	var (
		err  error
		node *Threat
	)
	if len(tc.hooks) == 0 {
		if err = tc.check(); err != nil {
			return nil, err
		}
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ThreatMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tc.check(); err != nil {
				return nil, err
			}
			tc.mutation = mutation
			if node, err = tc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			if tc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, tc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Threat)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ThreatMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *ThreatCreate) SaveX(ctx context.Context) *Threat {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *ThreatCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *ThreatCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *ThreatCreate) check() error {
	if _, ok := tc.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Threat.ip"`)}
	}
	if _, ok := tc.mutation.ThreatIDInfo(); !ok {
		return &ValidationError{Name: "threat_id_info", err: errors.New(`ent: missing required field "Threat.threat_id_info"`)}
	}
	if _, ok := tc.mutation.DomainCount(); !ok {
		return &ValidationError{Name: "domain_count", err: errors.New(`ent: missing required field "Threat.domain_count"`)}
	}
	if _, ok := tc.mutation.TagCount(); !ok {
		return &ValidationError{Name: "tag_count", err: errors.New(`ent: missing required field "Threat.tag_count"`)}
	}
	if _, ok := tc.mutation.ItelCount(); !ok {
		return &ValidationError{Name: "itel_count", err: errors.New(`ent: missing required field "Threat.itel_count"`)}
	}
	if _, ok := tc.mutation.Judge(); !ok {
		return &ValidationError{Name: "judge", err: errors.New(`ent: missing required field "Threat.judge"`)}
	}
	if _, ok := tc.mutation.Poc(); !ok {
		return &ValidationError{Name: "poc", err: errors.New(`ent: missing required field "Threat.poc"`)}
	}
	if _, ok := tc.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Threat.source"`)}
	}
	if _, ok := tc.mutation.Ctime(); !ok {
		return &ValidationError{Name: "ctime", err: errors.New(`ent: missing required field "Threat.ctime"`)}
	}
	return nil
}

func (tc *ThreatCreate) sqlSave(ctx context.Context) (*Threat, error) {
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (tc *ThreatCreate) createSpec() (*Threat, *sqlgraph.CreateSpec) {
	var (
		_node = &Threat{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: threat.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: threat.FieldID,
			},
		}
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tc.mutation.IP(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: threat.FieldIP,
		})
		_node.IP = value
	}
	if value, ok := tc.mutation.ThreatIDInfo(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: threat.FieldThreatIDInfo,
		})
		_node.ThreatIDInfo = value
	}
	if value, ok := tc.mutation.DomainCount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: threat.FieldDomainCount,
		})
		_node.DomainCount = value
	}
	if value, ok := tc.mutation.TagCount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: threat.FieldTagCount,
		})
		_node.TagCount = value
	}
	if value, ok := tc.mutation.ItelCount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: threat.FieldItelCount,
		})
		_node.ItelCount = value
	}
	if value, ok := tc.mutation.Judge(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: threat.FieldJudge,
		})
		_node.Judge = value
	}
	if value, ok := tc.mutation.Poc(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: threat.FieldPoc,
		})
		_node.Poc = value
	}
	if value, ok := tc.mutation.Source(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: threat.FieldSource,
		})
		_node.Source = value
	}
	if value, ok := tc.mutation.Ctime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: threat.FieldCtime,
		})
		_node.Ctime = value
	}
	return _node, _spec
}

// ThreatCreateBulk is the builder for creating many Threat entities in bulk.
type ThreatCreateBulk struct {
	config
	builders []*ThreatCreate
}

// Save creates the Threat entities in the database.
func (tcb *ThreatCreateBulk) Save(ctx context.Context) ([]*Threat, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Threat, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ThreatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *ThreatCreateBulk) SaveX(ctx context.Context) []*Threat {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *ThreatCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *ThreatCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
